language: node_js

node_js:
  - "0.11"
  - "0.10"

script:
  - "make test"

matrix:
  fast_finish: true

  include:
    - node_js: "0.10"
    - node_js: "0.11"
      env: COVERAGE=true

  allow_failures:
    - node_js: "0.10"
    - node_js: "0.11"
      env: COVERAGE=true