# Site settings
title: Waterlock
author: "David Rivera"
email: david.r.rivera193@gmail.com
description: "Waterlock documentation"
# baseurl: "http://davidrivera.github.io/waterlock/"
# url: "http://davidrivera.github.io/waterlock/"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: :compress
  sass_dir: _sass