# Site settings
title: Waterlock
email: david.r.rivera193@gmail.com
description: "Waterlock documentation"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: :compress